on: push
name: Check that system config applies
jobs:
  main_job:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}   
    steps:
      - name: Install configs
        run: |
          git clone https://github.com/keedhost/dotfiles.git
          bash dotfiles/bootstrap --noask
