on: push
name: Check that system config applies
jobs:
  git_clone:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
    runs-on: ${{ matrix.os }}   
    steps:
      - name: Clone ZSH configs
        uses: actions/checkout@v3
        with:
          repository: keedhost/zsh
          path: ${HOME}/.zsh

      - name: Clone vim configs
        uses: actions/checkout@v3
        with:
          repository: keedhost/vim
          path: ${HOME}/.vim

  main_job:
    env:
      IF_CI: true
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
    runs-on: ${{ matrix.os }}   
    steps:
      - name: Install configs
        run: |
          git clone https://github.com/keedhost/dotfiles.git
          bash dotfiles/bootstrap --noask
