name: Config validation
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
name: Run main test
jobs:
  main_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
     steps:
      - uses: actions/checkout@v3
      - name: Install configs
      run: |
        git clone https://github.com/keedhost/dotfiles.git
        cd dotfiles
        bash bootstrap --noask

