name: Config validation
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Run-on-ubuntu:
    name: Run on Ubuntu latest
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Clone repo
          run: |
            git clone https://github.com/keedhost/dotfiles.git
            cd dotfiles
            bash bootstrap --noask

  Run-on-macOS:
    name: Run on masOS latest
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v3
        - name: Clone repo
          run: |
            git clone https://github.com/keedhost/dotfiles.git
            cd dotfiles
            bash bootstrap --noask
